# k8s/service.yaml

apiVersion: v1
kind: Service
metadata:
  name: heart-disease-predictor-service
  labels:
    app: heart-api
spec:
  selector:
    app: heart-api
  ports:
    - name: http
      port: 80 # External port
      targetPort: 8000 # Container port
  type: NodePort
