# ci/github-actions-workflow.yml

name: MLOps CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Install Dependencies
      - name: Install Dependencies
        run:  |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Linting (FAILS pipeline on errors)
      - name: Lint code
        run: |
          flake8 src tests

      # 5. Data Acquisition (Step 1)
      - name: Download Data
        run: python data/download_dataset.py

      # 6. Model Training (Step 3) - Generates src/model/final_model.pkl
      - name: Train Model and Log with MLflow (Mock)
        # We don't need a real MLflow server for CI, just let the script run
        run: |
          python src/train.py | tee training.log

      # 7. Automated Testing (Step 6) - Runs the tests defined above
      - name: Run Pytest
        run: |
          pytest tests --disable-warnings -v | tee test.log

      # 8. Upload trained model artifact
      - name: Upload trained model
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: src/model/

      # 9. Upload MLflow experiment data
      - name: Upload MLflow runs
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-runs
          path: mlruns/

      # 10. Upload logs for this workflow run
      - name: Upload CI logs
        uses: actions/upload-artifact@v4
        with:
          name: ci-logs
          path: |
            training.log
            test.log

      - name: Cleanup Container
        if: always()
        run: docker rm -f heart_api_test